# Generated by Django 4.2.7 on 2023-11-30 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(default='system')),
                ('updation_date', models.DateTimeField(auto_now=True, null=True)),
                ('updation_by', models.TextField(null=True)),
            ],
            options={
                'db_table': 'location_detail',
            },
        ),
        migrations.CreateModel(
            name='LocationDetailLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='weather.locationdetail')),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(default='system')),
            ],
            options={
                'db_table': 'location_detail_log',
            },
        ),
    ]
